Console Error Server
FirebaseError: Failed to get document because the client is offline.

Call Stack
10

Hide 8 ignore-listed frame(s)
resolveErrorDev
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (1838:46)
getOutlinedModel
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (1322:22)
parseModelString
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (1462:15)
Array.<anonymous>
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (2267:18)
JSON.parse
<anonymous> (0:0)
resolveConsoleEntry
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (2102:28)
processFullStringRow
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (2243:11)
processFullBinaryRow
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (2206:7)
progress
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (2452:17)
Home
<anonymous> (0:0)