.
12 import { NoticeMessage } from 'pg-protocol/dist/messages';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:10:1 - error TS6133: 'onRequest' is declared but its value is never read.

10 import {onRequest} from "firebase-functions/v2/https";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:11:1 - error TS6133: 'logger' is declared but its value is never read.

11 import * as logger from "firebase-functions/logger";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 3 errors in 2 files.

Errors  Files
     1  node_modules/@types/pg/index.d.ts:12
     2  src/index.ts:10

Error: functions predeploy error: Command terminated with non-zero exit code 2